language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
  - php: 5.3
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: nightly

before_script:
  - scripts/configure_composer.sh
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 5.3"

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb
